name: 02-Enhanced workflow for deployment

on: 
  workflow_dispatch: 
    inputs:
      action:
        description: "Action to perform on the Kubernetes manifest (apply or delete)"
        default: none
        type: choice
        options:
          - apply
          - delete
        required: true

jobs:
  k8s-deployment-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Install gke-gcloud-auth-plugin
        run: |
            gcloud components install gke-gcloud-auth-plugin
      
      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
          --zone us-east1-b


      - name: Apply K8s manifest file
        if: ${{ inputs.action == 'apply' }}
        run: |
            kubectl apply -f nginx-deployment.yaml
      - name: Delete the k8s manifest file
        if: ${{ inputs.action == 'delete' }}
        run: |
            kubectl delete -f nginx-deployment.yaml
      
      - name: Check Deployment Rollout Status
        run: |
            kubectl rollout status deployment/nginx-deployment
          